import { buildCanonicalConversationMemory, buildConversationMemoryMarkdown, reconcileDeliveredMemoryReply } from "../../supabase/functions/_shared/conversation-long-memory.ts";
import { createEmptyConversationCommerceState } from "../../supabase/functions/_shared/commerce-state-contract.ts";
const assert=(condition:unknown,message:string)=>{if(!condition)throw new Error(message);};
const cid="fd070000-0000-4000-8000-000000000002",co="fd070000-0000-4000-8000-000000000001",source="fd070000-0000-4000-8000-000000000003",reply="fd070000-0000-4000-8000-000000000004";
async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,"0")).join("");}
function setup(kind:string,mode="success") {
 const commerce=createEmptyConversationCommerceState();
 const customer={id:source,conversation_id:cid,role:"visitor",content:"Can this custom service accommodate a morning visit?"};
 const answer={id:reply,conversation_id:cid,role:"assistant",content:kind==="grounded"?"The documented service window includes morning visits.":"Which day would you prefer?",is_recalled:false,metadata:{source_message_id:source,b2_source_message_id:source,b2_commit_source:"commit_ai_reply_tx",control_commit:"ai",b2_expected_company_id:co,b2_expected_revision:1,b2_gate_contract:"executeB2PersistenceGate:allow_after_revalidation",response_route:kind==="grounded"?"canonical_kb_direct_answer":kind==="guidance"?"product_guidance":"contextual_clarification",service_action:kind==="grounded"?"direct_answer":"targeted_clarification"}};
 const memory=buildCanonicalConversationMemory({conversation_id:cid,company_id:co,source_message_id:source,commerce_state_revision:1,commerce_state:commerce,newest_first:[customer],visitor_turn_count:1,source_created_at:"2026-10-07T00:00:00Z",next_memory_revision:1});
 let state:any={conversation_id:cid,company_id:co,source_message_id:source,revision:1,commerce_state_revision:1,memory,markdown_projection:buildConversationMemoryMarkdown(memory),memory_hash:"a".repeat(64)};
 const parent={conversation_id:cid,company_id:co,source_message_id:source,applied_revision:1,commerce_state_revision:1,memory_hash:"a".repeat(64)};
 let receipt:any=null;
 const calls:Array<{name:string;args:any}>=[];
 const client={from(table:string){const filters:any={};const query:any={select(){return query;},eq(k:string,v:any){filters[k]=v;return query;},async maybeSingle(){let data:any=table==="messages"?(filters.id===reply?answer:customer):table==="conversation_memory_state"?state:table==="conversation_memory_state_event"?parent:table==="c3_memory_reply_lifecycle_receipt"?receipt:table==="conversation_commerce_state"?{revision:1,state:commerce}:null; if(mode==="missing-reply"&&table==="messages"&&filters.id===reply)data=null;return {data,error:null};}};return query;},async rpc(name:string,args:any){calls.push({name,args});assert(name==="c3_finalize_memory_reply_tx","old conflicting RPC reused");assert(args.p_reply_message_id===reply&&args.p_expected_memory_hash===parent.memory_hash,"parent/reply ownership missing");if(mode==="rejected")return{data:{result:"revision_conflict"},error:null};state={...state,revision:2,memory:args.p_memory,markdown_projection:args.p_markdown_projection,memory_hash:"b".repeat(64)};receipt={...parent,reply_message_id:reply,parent_revision:1,parent_hash:parent.memory_hash,applied_revision:2,memory_hash:state.memory_hash,markdown_hash:await hash(state.markdown_projection),reply_content_hash:await hash(answer.content)};if(mode==="conflicting-receipt")receipt.parent_hash="c".repeat(64);if(mode==="lost-ack")throw new Error("lost acknowledgement");return{data:{result:"success"},error:null};}};
 return{client,calls,parent,args:{conversation_id:cid,source_message_id:source,reply_message_id:reply}};
}
for(const kind of ["clarification","grounded","guidance"])Deno.test("actual caller: "+kind+" uses distinct assistant receipt and is retry-safe",async()=>{const f=setup(kind);const before=JSON.stringify(f.parent);assert(await reconcileDeliveredMemoryReply(f.client,f.args),"initial reconcile failed");assert(await reconcileDeliveredMemoryReply(f.client,f.args),"retry failed");assert(f.calls.length===1,"retry rewrote lifecycle");assert(JSON.stringify(f.parent)===before,"customer receipt changed");});
Deno.test("actual caller: lost RPC acknowledgement requires exact receipt readback",async()=>{const f=setup("guidance","lost-ack");assert(await reconcileDeliveredMemoryReply(f.client,f.args),"committed transport recovery failed");});
for(const mode of ["rejected","conflicting-receipt","missing-reply"])Deno.test("actual caller fails closed: "+mode,async()=>{const f=setup("guidance",mode);assert(!(await reconcileDeliveredMemoryReply(f.client,f.args)),"rejection converted into success");});
