#!/bin/bash
set -Eeuo pipefail

L="scripts/pr12-product-ready-activation-loader.py"
C="scripts/pr12-product-ready-activate.command"
E="config/pr12-production-activation.example.json"
R="scripts/pr11-final-product-ready-integration-runner.sh"
P="scripts/pr11-final-product-ready-integration-preflight.sh"
CFG="scripts/pr7-production-runtime-config-gate.sh"

fail=0
pass(){ echo "PASS $1"; }; bad(){ echo "FAIL $1"; fail=1; }
has(){ grep -Fq "$2" "$1" && pass "$3" || bad "$3"; }
not_has(){ grep -Fq "$2" "$1" && bad "$3" || pass "$3"; }

for f in "$L" "$C" "$E" "$R" "$P" "$CFG"; do
  [ -s "$f" ] || { echo "FAIL missing/empty $f"; exit 1; }
done

has "$L" 'activation JSON must live OUTSIDE the Git repository' "private activation file must stay outside repo"
has "$L" 'require chmod 600' "private activation file requires owner-only permissions"
has "$L" 'os.execvpe("bash"' "loader passes validated values by process environment"
not_has "$L" 'eval(' "loader never evals activation values"
not_has "$L" 'print(values' "loader never prints activation values"
not_has "$L" 'write_text(' "loader never writes secrets to disk"

has "$L" 'PR7_CANONICAL_COMPANY_UUID' "canonical UUID parameter included"
has "$L" 'PR7_CANONICAL_PLATFORM_COMPANY_ID' "canonical integer company id included"
has "$L" 'PR11_AUTHORIZED_SOURCE_COMMIT' "authorized source commit included"
has "$L" 'PR7_ROLLBACK_COMMIT' "rollback commit included"
has "$L" 'KB_SINGAPORE_TENANT_MAP_JSON' "Singapore mapping included"
has "$L" 'PR8_CE_SMOKE_FIXTURE_APPROVED' "CE runtime fixture contract included"
has "$L" 'PR10_TWO_TENANT_FIXTURES_APPROVED' "two-tenant runtime fixture contract included"
has "$L" 'PR11_PRIMARY_ACCEPTANCE_USER_UUID' "canonical role acceptance user included"

has "$L" 'PR7_TEST_USER_A","PR10_TENANT_A_USER_UUID' "legacy PR7 and PR10 Tenant A user fixture locked together"
has "$L" 'PR7_TEST_COMPANY_A","PR10_TENANT_A_COMPANY_UUID' "legacy PR7 and PR10 Tenant A company fixture locked together"
has "$L" 'PR7_TEST_USER_B","PR10_TENANT_B_USER_UUID' "legacy PR7 and PR10 Tenant B user fixture locked together"
has "$L" 'PR7_TEST_COMPANY_B","PR10_TENANT_B_COMPANY_UUID' "legacy PR7 and PR10 Tenant B company fixture locked together"

has "$C" 'pr12-product-ready-activation-loader.py' "one-command wrapper delegates to safe loader"
has "$R" 'pr11-final-integration-source-lock.sh' "existing final runner still locks authorized source"
has "$R" 'pr7-production-deploy.sh' "existing final runner still delegates writes atomically"

python3 - "$E" "$L" <<'PY' || { bad "example activation contract exactly matches loader key set"; }
import ast,json,re,sys
e=json.load(open(sys.argv[1],encoding="utf-8"))
text=open(sys.argv[2],encoding="utf-8").read()
m=re.search(r'^REQUIRED = (\[.*?\])$',text,re.M|re.S)
if not m: raise SystemExit(1)
required=ast.literal_eval(m.group(1))
m2=re.search(r'^OPTIONAL = (\{.*?\})$',text,re.M)
if not m2: raise SystemExit(1)
optional=ast.literal_eval(m2.group(1))
if set(e) != set(required)|set(optional):
    raise SystemExit(1)
if any(k not in e for k in required):
    raise SystemExit(1)
print("PASS example activation JSON covers exact loader contract")
PY

# Cross-check loadable contract contains all environment names consumed by the
# frozen final preflight and production runtime config, excluding only internal
# shell locals and variables generated by those scripts.
python3 - "$L" "$P" "$CFG" <<'PY' || { bad "activation contract covers frozen final/runtime parameters"; }
import ast,re,sys
loader=open(sys.argv[1],encoding="utf-8").read()
m=re.search(r'^REQUIRED = (\[.*?\])$',loader,re.M|re.S)
required=set(ast.literal_eval(m.group(1)))
optional={"KB_SINGAPORE_JWT_TTL_SEC","PR7_FUNCTIONS_URL"}
covered=required|optional
texts=[open(p,encoding="utf-8").read() for p in sys.argv[2:]]
# Explicit production-facing names that must be present in loader contract.
must={
"PR11_FINAL_PRODUCT_READY_INTEGRATION_AUTHORIZED","PR7_PRODUCTION_DEPLOY_AUTHORIZED",
"PR7_PROJECT_REF","SUPABASE_DB_URL","SUPABASE_ACCESS_TOKEN","PR7_ROLLBACK_COMMIT",
"PR7_CANONICAL_COMPANY_UUID","PR7_CANONICAL_PLATFORM_COMPANY_ID",
"KB_SINGAPORE_TENANT_MAP_JSON","KB_SINGAPORE_JWT_SECRET",
"ENABLE_KB_ADAPTER","ENABLE_CUSTOMER360_ADAPTER","ENABLE_COACH_PROMPT_ADAPTER",
"ANTHROPIC_API_KEY","CUSTOMER360_INTERNAL_TOKEN","CUSTOMER360_API_URL","CUSTOMER360_API_TOKEN",
"COACH_PROMPT_ENDPOINT","COACH_PROMPT_INTERNAL_TOKEN","C360_COACH_SYNC_INTERNAL_TOKEN",
"COACH_C360_SYNC_API_URL","COACH_C360_SYNC_API_TOKEN","C360_COACH_SYNC_CONTRACT_VERSION",
"CE_CONTRACT_VERSION","CE_SOURCE_DEPLOYMENT","LLM_MODEL_EVALUATION",
"SU_COACHAI_EVALUATION_ENDPOINT","SU_COACHAI_AUTH_HEADER","SU_COACHAI_AUTH_VALUE",
"TRAINING_OUTBOX_INTERNAL_TOKEN","SU_COACHAI_RESULT_TOKEN"
}
if not must <= covered:
    print("missing",sorted(must-covered)); raise SystemExit(1)
for name in must:
    if not any(name in t for t in texts):
        print("not consumed by frozen preflight/runtime config",name); raise SystemExit(1)
print("PASS activation contract covers frozen production-facing runtime parameters")
PY

if [ "$fail" -ne 0 ]; then
  echo "TASK 12.2 ACTIVATION PARAMETER CONTRACT SOURCE STATUS: FAIL"
  exit 1
fi
echo "TASK 12.2 ACTIVATION PARAMETER CONTRACT SOURCE STATUS: PASS"
