/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedConsoleIndexRouteImport } from './routes/_authenticated/console.index'
import { Route as AuthenticatedConsoleWidgetPreviewRouteImport } from './routes/_authenticated/console.widget-preview'
import { Route as AuthenticatedConsoleTrainingCandidatesRouteImport } from './routes/_authenticated/console.training-candidates'
import { Route as AuthenticatedConsoleKbGapsRouteImport } from './routes/_authenticated/console.kb-gaps'
import { Route as AuthenticatedConsoleFeedbackSettingsRouteImport } from './routes/_authenticated/console.feedback-settings'
import { Route as AuthenticatedConsoleCustomer360RouteImport } from './routes/_authenticated/console.customer360'
import { Route as AuthenticatedConsoleChannelSettingsRouteImport } from './routes/_authenticated/console.channel-settings'
import { Route as AuthenticatedConsoleAnalyticsRouteImport } from './routes/_authenticated/console.analytics'
import { Route as AuthenticatedConsoleAgentSettingsRouteImport } from './routes/_authenticated/console.agent-settings'
import { Route as AuthenticatedConsoleSplatRouteImport } from './routes/_authenticated/console.$'
import { Route as AuthenticatedConsoleConversationsIndexRouteImport } from './routes/_authenticated/console.conversations.index'
import { Route as AuthenticatedConsoleSettingsLlmRuntimeRouteImport } from './routes/_authenticated/console.settings.llm-runtime'
import { Route as AuthenticatedConsoleConversationsIdRouteImport } from './routes/_authenticated/console.conversations.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleWidgetPreviewRoute =
  AuthenticatedConsoleWidgetPreviewRouteImport.update({
    id: '/widget-preview',
    path: '/widget-preview',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleTrainingCandidatesRoute =
  AuthenticatedConsoleTrainingCandidatesRouteImport.update({
    id: '/training-candidates',
    path: '/training-candidates',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleKbGapsRoute =
  AuthenticatedConsoleKbGapsRouteImport.update({
    id: '/kb-gaps',
    path: '/kb-gaps',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleFeedbackSettingsRoute =
  AuthenticatedConsoleFeedbackSettingsRouteImport.update({
    id: '/feedback-settings',
    path: '/feedback-settings',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleCustomer360Route =
  AuthenticatedConsoleCustomer360RouteImport.update({
    id: '/customer360',
    path: '/customer360',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleChannelSettingsRoute =
  AuthenticatedConsoleChannelSettingsRouteImport.update({
    id: '/channel-settings',
    path: '/channel-settings',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleAnalyticsRoute =
  AuthenticatedConsoleAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleAgentSettingsRoute =
  AuthenticatedConsoleAgentSettingsRouteImport.update({
    id: '/agent-settings',
    path: '/agent-settings',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSplatRoute =
  AuthenticatedConsoleSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleConversationsIndexRoute =
  AuthenticatedConsoleConversationsIndexRouteImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSettingsLlmRuntimeRoute =
  AuthenticatedConsoleSettingsLlmRuntimeRouteImport.update({
    id: '/settings/llm-runtime',
    path: '/settings/llm-runtime',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleConversationsIdRoute =
  AuthenticatedConsoleConversationsIdRouteImport.update({
    id: '/conversations/$id',
    path: '/conversations/$id',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/console': typeof AuthenticatedConsoleRouteWithChildren
  '/console/$': typeof AuthenticatedConsoleSplatRoute
  '/console/agent-settings': typeof AuthenticatedConsoleAgentSettingsRoute
  '/console/analytics': typeof AuthenticatedConsoleAnalyticsRoute
  '/console/channel-settings': typeof AuthenticatedConsoleChannelSettingsRoute
  '/console/customer360': typeof AuthenticatedConsoleCustomer360Route
  '/console/feedback-settings': typeof AuthenticatedConsoleFeedbackSettingsRoute
  '/console/kb-gaps': typeof AuthenticatedConsoleKbGapsRoute
  '/console/training-candidates': typeof AuthenticatedConsoleTrainingCandidatesRoute
  '/console/widget-preview': typeof AuthenticatedConsoleWidgetPreviewRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
  '/console/conversations/$id': typeof AuthenticatedConsoleConversationsIdRoute
  '/console/settings/llm-runtime': typeof AuthenticatedConsoleSettingsLlmRuntimeRoute
  '/console/conversations/': typeof AuthenticatedConsoleConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/console/$': typeof AuthenticatedConsoleSplatRoute
  '/console/agent-settings': typeof AuthenticatedConsoleAgentSettingsRoute
  '/console/analytics': typeof AuthenticatedConsoleAnalyticsRoute
  '/console/channel-settings': typeof AuthenticatedConsoleChannelSettingsRoute
  '/console/customer360': typeof AuthenticatedConsoleCustomer360Route
  '/console/feedback-settings': typeof AuthenticatedConsoleFeedbackSettingsRoute
  '/console/kb-gaps': typeof AuthenticatedConsoleKbGapsRoute
  '/console/training-candidates': typeof AuthenticatedConsoleTrainingCandidatesRoute
  '/console/widget-preview': typeof AuthenticatedConsoleWidgetPreviewRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
  '/console/conversations/$id': typeof AuthenticatedConsoleConversationsIdRoute
  '/console/settings/llm-runtime': typeof AuthenticatedConsoleSettingsLlmRuntimeRoute
  '/console/conversations': typeof AuthenticatedConsoleConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRouteWithChildren
  '/_authenticated/console/$': typeof AuthenticatedConsoleSplatRoute
  '/_authenticated/console/agent-settings': typeof AuthenticatedConsoleAgentSettingsRoute
  '/_authenticated/console/analytics': typeof AuthenticatedConsoleAnalyticsRoute
  '/_authenticated/console/channel-settings': typeof AuthenticatedConsoleChannelSettingsRoute
  '/_authenticated/console/customer360': typeof AuthenticatedConsoleCustomer360Route
  '/_authenticated/console/feedback-settings': typeof AuthenticatedConsoleFeedbackSettingsRoute
  '/_authenticated/console/kb-gaps': typeof AuthenticatedConsoleKbGapsRoute
  '/_authenticated/console/training-candidates': typeof AuthenticatedConsoleTrainingCandidatesRoute
  '/_authenticated/console/widget-preview': typeof AuthenticatedConsoleWidgetPreviewRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
  '/_authenticated/console/conversations/$id': typeof AuthenticatedConsoleConversationsIdRoute
  '/_authenticated/console/settings/llm-runtime': typeof AuthenticatedConsoleSettingsLlmRuntimeRoute
  '/_authenticated/console/conversations/': typeof AuthenticatedConsoleConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/console'
    | '/console/$'
    | '/console/agent-settings'
    | '/console/analytics'
    | '/console/channel-settings'
    | '/console/customer360'
    | '/console/feedback-settings'
    | '/console/kb-gaps'
    | '/console/training-candidates'
    | '/console/widget-preview'
    | '/console/'
    | '/console/conversations/$id'
    | '/console/settings/llm-runtime'
    | '/console/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/console/$'
    | '/console/agent-settings'
    | '/console/analytics'
    | '/console/channel-settings'
    | '/console/customer360'
    | '/console/feedback-settings'
    | '/console/kb-gaps'
    | '/console/training-candidates'
    | '/console/widget-preview'
    | '/console'
    | '/console/conversations/$id'
    | '/console/settings/llm-runtime'
    | '/console/conversations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/console'
    | '/_authenticated/console/$'
    | '/_authenticated/console/agent-settings'
    | '/_authenticated/console/analytics'
    | '/_authenticated/console/channel-settings'
    | '/_authenticated/console/customer360'
    | '/_authenticated/console/feedback-settings'
    | '/_authenticated/console/kb-gaps'
    | '/_authenticated/console/training-candidates'
    | '/_authenticated/console/widget-preview'
    | '/_authenticated/console/'
    | '/_authenticated/console/conversations/$id'
    | '/_authenticated/console/settings/llm-runtime'
    | '/_authenticated/console/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/widget-preview': {
      id: '/_authenticated/console/widget-preview'
      path: '/widget-preview'
      fullPath: '/console/widget-preview'
      preLoaderRoute: typeof AuthenticatedConsoleWidgetPreviewRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/training-candidates': {
      id: '/_authenticated/console/training-candidates'
      path: '/training-candidates'
      fullPath: '/console/training-candidates'
      preLoaderRoute: typeof AuthenticatedConsoleTrainingCandidatesRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/kb-gaps': {
      id: '/_authenticated/console/kb-gaps'
      path: '/kb-gaps'
      fullPath: '/console/kb-gaps'
      preLoaderRoute: typeof AuthenticatedConsoleKbGapsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/feedback-settings': {
      id: '/_authenticated/console/feedback-settings'
      path: '/feedback-settings'
      fullPath: '/console/feedback-settings'
      preLoaderRoute: typeof AuthenticatedConsoleFeedbackSettingsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/customer360': {
      id: '/_authenticated/console/customer360'
      path: '/customer360'
      fullPath: '/console/customer360'
      preLoaderRoute: typeof AuthenticatedConsoleCustomer360RouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/channel-settings': {
      id: '/_authenticated/console/channel-settings'
      path: '/channel-settings'
      fullPath: '/console/channel-settings'
      preLoaderRoute: typeof AuthenticatedConsoleChannelSettingsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/analytics': {
      id: '/_authenticated/console/analytics'
      path: '/analytics'
      fullPath: '/console/analytics'
      preLoaderRoute: typeof AuthenticatedConsoleAnalyticsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/agent-settings': {
      id: '/_authenticated/console/agent-settings'
      path: '/agent-settings'
      fullPath: '/console/agent-settings'
      preLoaderRoute: typeof AuthenticatedConsoleAgentSettingsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/$': {
      id: '/_authenticated/console/$'
      path: '/$'
      fullPath: '/console/$'
      preLoaderRoute: typeof AuthenticatedConsoleSplatRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/conversations/': {
      id: '/_authenticated/console/conversations/'
      path: '/conversations'
      fullPath: '/console/conversations/'
      preLoaderRoute: typeof AuthenticatedConsoleConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/settings/llm-runtime': {
      id: '/_authenticated/console/settings/llm-runtime'
      path: '/settings/llm-runtime'
      fullPath: '/console/settings/llm-runtime'
      preLoaderRoute: typeof AuthenticatedConsoleSettingsLlmRuntimeRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/conversations/$id': {
      id: '/_authenticated/console/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/console/conversations/$id'
      preLoaderRoute: typeof AuthenticatedConsoleConversationsIdRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
  }
}

interface AuthenticatedConsoleRouteChildren {
  AuthenticatedConsoleSplatRoute: typeof AuthenticatedConsoleSplatRoute
  AuthenticatedConsoleAgentSettingsRoute: typeof AuthenticatedConsoleAgentSettingsRoute
  AuthenticatedConsoleAnalyticsRoute: typeof AuthenticatedConsoleAnalyticsRoute
  AuthenticatedConsoleChannelSettingsRoute: typeof AuthenticatedConsoleChannelSettingsRoute
  AuthenticatedConsoleCustomer360Route: typeof AuthenticatedConsoleCustomer360Route
  AuthenticatedConsoleFeedbackSettingsRoute: typeof AuthenticatedConsoleFeedbackSettingsRoute
  AuthenticatedConsoleKbGapsRoute: typeof AuthenticatedConsoleKbGapsRoute
  AuthenticatedConsoleTrainingCandidatesRoute: typeof AuthenticatedConsoleTrainingCandidatesRoute
  AuthenticatedConsoleWidgetPreviewRoute: typeof AuthenticatedConsoleWidgetPreviewRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
  AuthenticatedConsoleConversationsIdRoute: typeof AuthenticatedConsoleConversationsIdRoute
  AuthenticatedConsoleSettingsLlmRuntimeRoute: typeof AuthenticatedConsoleSettingsLlmRuntimeRoute
  AuthenticatedConsoleConversationsIndexRoute: typeof AuthenticatedConsoleConversationsIndexRoute
}

const AuthenticatedConsoleRouteChildren: AuthenticatedConsoleRouteChildren = {
  AuthenticatedConsoleSplatRoute: AuthenticatedConsoleSplatRoute,
  AuthenticatedConsoleAgentSettingsRoute:
    AuthenticatedConsoleAgentSettingsRoute,
  AuthenticatedConsoleAnalyticsRoute: AuthenticatedConsoleAnalyticsRoute,
  AuthenticatedConsoleChannelSettingsRoute:
    AuthenticatedConsoleChannelSettingsRoute,
  AuthenticatedConsoleCustomer360Route: AuthenticatedConsoleCustomer360Route,
  AuthenticatedConsoleFeedbackSettingsRoute:
    AuthenticatedConsoleFeedbackSettingsRoute,
  AuthenticatedConsoleKbGapsRoute: AuthenticatedConsoleKbGapsRoute,
  AuthenticatedConsoleTrainingCandidatesRoute:
    AuthenticatedConsoleTrainingCandidatesRoute,
  AuthenticatedConsoleWidgetPreviewRoute:
    AuthenticatedConsoleWidgetPreviewRoute,
  AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
  AuthenticatedConsoleConversationsIdRoute:
    AuthenticatedConsoleConversationsIdRoute,
  AuthenticatedConsoleSettingsLlmRuntimeRoute:
    AuthenticatedConsoleSettingsLlmRuntimeRoute,
  AuthenticatedConsoleConversationsIndexRoute:
    AuthenticatedConsoleConversationsIndexRoute,
}

const AuthenticatedConsoleRouteWithChildren =
  AuthenticatedConsoleRoute._addFileChildren(AuthenticatedConsoleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleRoute: AuthenticatedConsoleRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
