// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { resolveAuthoritativeSupabaseBinding } from './runtime-authority.mjs'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    // The user-owned Supabase project is the only authoritative runtime.
    const binding = resolveAuthoritativeSupabaseBinding({
      url: process.env.SUPABASE_URL,
      projectId: process.env.SUPABASE_PROJECT_ID,
      publishableKey: process.env.SUPABASE_PUBLISHABLE_KEY,
    });
    const SUPABASE_URL = binding.url;
    const SUPABASE_PUBLISHABLE_KEY = binding.publishableKey;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const message = '[Supabase] Missing authoritative Supabase runtime binding.';
      console.error(message);
      throw new Error(message);
    }
    
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
