/**
 * Conversation Evaluation — schema types for the console.
 *
 * src/integrations/supabase/types.ts is generated by the platform and is
 * regenerated on schema migration. Until that regeneration runs, the columns
 * added by 20260728093000_ce_task1 are absent from it. Editing a generated file
 * by hand would be overwritten silently, so the new surface is declared here as
 * a typed overlay instead, and the route consumes a properly typed client
 * rather than an untyped `SupabaseClient` escape hatch.
 *
 * When the generated file catches up, delete this overlay and re-point
 * `ceClient` at the generated `Database` type. The row interfaces below are the
 * contract the route relies on either way.
 */

import type { SupabaseClient } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";

export type ReviewStatus = "pending" | "accepted" | "rejected";
export type Severity = "critical" | "high" | "medium" | "low";
export type EvaluatorType = "accuracy" | "policy" | "tone" | "sales" | "context" | "hallucination";
export type AttemptStatus = "running" | "complete" | "failed" | "persistence_error";

export interface ConversationEvaluationRow {
  id: string;
  conversation_id: string;
  company_id: string | null;
  attempt_id: string;
  evaluation_contract_version: string;
  input_snapshot_hash: string;
  bundle_hash: string | null;
  accuracy_score: number;
  policy_score: number;
  tone_score: number;
  sales_score: number;
  context_score: number;
  hallucination_risk_score: number;
  overall_score: number;
  severity: Severity;
  has_verified_human_response: boolean;
  training_eligible: boolean;
  model_version: string;
  prompt_version: string;
  kb_snapshot_id: string;
  policy_snapshot_id: string;
  source_deployment: string;
  review_status: ReviewStatus;
  review_note: string | null;
  reviewed_by: string | null;
  reviewed_at: string | null;
  created_at: string;
}

export interface ConversationEvaluationDetailRow {
  evaluation_id: string;
  evaluator_type: EvaluatorType;
  raw_score: number;
  weight: number;
  weighted_score: number;
  justification: string | null;
  recommended_correction: string | null;
  evaluator_model_version: string | null;
  evaluator_prompt_version: string | null;
  grounding_refs: string[] | null;
}

export interface ConversationEvaluationAttemptRow {
  id: string;
  conversation_id: string;
  status: AttemptStatus;
  error_message: string | null;
  created_at: string;
  updated_at: string;
}

export interface TrainingOutboxRow {
  id: string;
  evaluation_id: string;
  status: "pending" | "in_progress" | "delivered" | "failed" | "skipped";
  delivery_attempts: number;
  max_attempts: number;
  delivered_at: string | null;
  created_at: string;
}

export interface ConversationRow {
  id: string;
  company_id: string | null;
  status: string;
  priority: string | null;
  channel_config_id: string | null;
  tags: string[] | null;
  created_at: string;
  updated_at: string;
  resolved_at: string | null;
}

export interface MessageRow {
  id: string;
  conversation_id: string;
  role: string;
  content: string;
  created_at: string;
  is_recalled: boolean;
  sender_id: string | null;
  sender_identity_verified_at: string | null;
}

export interface AuditLogRow {
  id: string;
  actor_id: string | null;
  action: string;
  resource_type: string;
  resource_id: string | null;
  diff: Record<string, unknown> | null;
  created_at: string;
}

export interface BundleSnapshotRow {
  id: string;
  attempt_id: string;
  conversation_id: string;
  company_id: string;
  bundle_hash: string;
  transcript_hash: string;
  evaluation_contract_version: string;
  model_version: string;
  prompt_version: string;
  kb_snapshot_id: string;
  policy_snapshot_id: string;
  canonical_input: string;
  grounding_evidence: {
    kb_block: string;
    policy_block: string;
    kb_snapshot_id: string;
    policy_snapshot_id: string;
  };
  normalized_transcript: Array<{
    id: string; role: string; raw_role: string; created_at: string;
    content: string; content_sha256: string; original_chars: number; used_chars: number;
  }>;
  evaluated_ai_reply: { id: string; created_at: string; content_sha256: string; content: string } | null;
  verified_human_response: { id: string; created_at: string; content_sha256: string; content: string } | null;
  grounding_manifest: Record<string, unknown>;
  truncation_manifest: Record<string, unknown>;
  redaction_applied: boolean;
  retention_expires_at: string;
  created_at: string;
}

export interface EmotionPointRow {
  id: string;
  evaluation_id: string;
  message_id: string;
  turn_index: number;
  occurred_at: string;
  sentiment: "very_negative" | "negative" | "neutral" | "positive" | "very_positive";
  sentiment_score: number;
  trigger_label: string | null;
}

export interface NextStepRow {
  id: string;
  evaluation_id: string;
  ordinal: number;
  title: string;
  detail: string | null;
  owner_role: string | null;
  status: "open" | "done" | "dismissed";
}

export interface DiscrepancyRow {
  id: string;
  evaluation_id: string;
  dimension: EvaluatorType;
  ai_claim: string;
  human_claim: string | null;
  grounded_claim: string | null;
  divergence_kind: "contradiction" | "omission" | "overreach" | "unsupported" | "style";
  severity: Severity;
  grounding_refs: string[] | null;
}

export interface RootCauseRow {
  id: string;
  evaluation_id: string;
  category: string;
  summary: string;
  evidence_refs: string[] | null;
  recorded_by: string;
  remote_sync_state: "pending" | "synced" | "failed" | "not_applicable";
  remote_ref: string | null;
  created_at: string;
}

export interface QaCaseRow {
  id: string;
  evaluation_id: string;
  case_number: string;
  title: string;
  description: string | null;
  status: "open" | "in_progress" | "resolved" | "closed";
  priority: "urgent" | "high" | "medium" | "low";
  remote_sync_state: "pending" | "synced" | "failed" | "not_applicable";
  remote_ref: string | null;
  created_at: string;
}

export interface KbPublishStateRow {
  id: string;
  evaluation_id: string;
  kb_document_ref: string;
  action: "publish" | "rollback";
  state: "requested" | "in_progress" | "published" | "rolled_back" | "failed";
  remote_sync_state: "pending" | "synced" | "failed" | "not_applicable";
  remote_ref: string | null;
  last_error: string | null;
  created_at: string;
}

export interface TrainingLinkRow {
  id: string;
  evaluation_id: string;
  link_kind: "training_candidate" | "kb_gap";
  local_state: "proposed" | "accepted" | "rejected" | "delivered";
  payload: Record<string, unknown>;
  improved_result: Record<string, unknown> | null;
  improved_state: "pending" | "received" | "not_applicable";
  remote_sync_state: "pending" | "synced" | "failed" | "not_applicable";
  remote_ref: string | null;
  updated_at: string;
}

export interface ChannelConfigRow {
  id: string;
  name: string;
  channel_type: string;
  company_id: string | null;
}

/** Minimal relational shape the console reads. Writes are not modelled: every
 *  CE table denies INSERT, UPDATE and DELETE to `authenticated`. */
export interface CeDatabase {
  public: {
    Tables: {
      conversation_evaluation: { Row: ConversationEvaluationRow };
      conversation_evaluation_detail: { Row: ConversationEvaluationDetailRow };
      conversation_evaluation_attempt: { Row: ConversationEvaluationAttemptRow };
      evaluation_training_outbox: { Row: TrainingOutboxRow };
      conversations: { Row: ConversationRow };
      messages: { Row: MessageRow };
      audit_log: { Row: AuditLogRow };
      channel_config: { Row: ChannelConfigRow };
      ce_bundle_snapshot: { Row: BundleSnapshotRow };
      ce_emotion_point: { Row: EmotionPointRow };
      ce_next_step: { Row: NextStepRow };
      ce_discrepancy: { Row: DiscrepancyRow };
      ce_root_cause: { Row: RootCauseRow };
      ce_qa_case: { Row: QaCaseRow };
      ce_kb_publish_state: { Row: KbPublishStateRow };
      ce_training_link: { Row: TrainingLinkRow };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      review_status: ReviewStatus;
      severity: Severity;
      evaluator_type: EvaluatorType;
    };
    CompositeTypes: Record<string, never>;
  };
}

/** Typed handle over the shared browser client. */
export const ceClient = supabase as unknown as SupabaseClient<CeDatabase>;

/** Column projections. raw_llm_response is deliberately absent everywhere. */
export const EVALUATION_COLUMNS =
  "id, conversation_id, company_id, attempt_id, evaluation_contract_version, input_snapshot_hash, bundle_hash, " +
  "accuracy_score, policy_score, tone_score, sales_score, context_score, hallucination_risk_score, " +
  "overall_score, severity, has_verified_human_response, training_eligible, model_version, prompt_version, " +
  "kb_snapshot_id, policy_snapshot_id, source_deployment, review_status, review_note, reviewed_by, " +
  "reviewed_at, created_at";

export const DETAIL_COLUMNS =
  "evaluation_id, evaluator_type, raw_score, weight, weighted_score, justification, " +
  "recommended_correction, evaluator_model_version, evaluator_prompt_version, grounding_refs";

export const ATTEMPT_COLUMNS = "id, conversation_id, status, error_message, created_at, updated_at";

export const OUTBOX_COLUMNS =
  "id, evaluation_id, status, delivery_attempts, max_attempts, delivered_at, created_at";

export const SNAPSHOT_COLUMNS =
  "id, attempt_id, conversation_id, company_id, bundle_hash, transcript_hash, " +
  "evaluation_contract_version, model_version, prompt_version, kb_snapshot_id, policy_snapshot_id, " +
  "normalized_transcript, evaluated_ai_reply, verified_human_response, grounding_manifest, " +
  "truncation_manifest, redaction_applied, retention_expires_at, created_at";
export const EMOTION_COLUMNS = "id, evaluation_id, message_id, turn_index, occurred_at, sentiment, sentiment_score, trigger_label";
export const NEXT_STEP_COLUMNS = "id, evaluation_id, ordinal, title, detail, owner_role, status";
export const DISCREPANCY_COLUMNS = "id, evaluation_id, dimension, ai_claim, human_claim, grounded_claim, divergence_kind, severity, grounding_refs";
export const ROOT_CAUSE_COLUMNS = "id, evaluation_id, category, summary, evidence_refs, recorded_by, remote_sync_state, remote_ref, created_at";
export const QA_CASE_COLUMNS = "id, evaluation_id, case_number, title, description, status, priority, remote_sync_state, remote_ref, created_at";
export const KB_PUBLISH_COLUMNS = "id, evaluation_id, kb_document_ref, action, state, remote_sync_state, remote_ref, last_error, created_at";
export const TRAINING_LINK_COLUMNS = "id, evaluation_id, link_kind, local_state, payload, improved_result, improved_state, remote_sync_state, remote_ref, updated_at";
