// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import {
  assertAuthoritativeFunctionsRuntime,
  assertAuthoritativeSupabaseRuntime,
  resolveAuthoritativeSupabaseBinding,
} from './runtime-authority.mjs';

function createSupabaseClient() {
  // GitHub/main + the user-owned Supabase project are authoritative.
  // Lovable may preview this source, but must never substitute its own backend:
  // any injected non-authoritative binding is discarded here.
  const binding = resolveAuthoritativeSupabaseBinding({
    url: import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL,
    projectId:
      import.meta.env.VITE_SUPABASE_PROJECT_ID || process.env.SUPABASE_PROJECT_ID,
    publishableKey:
      import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      process.env.SUPABASE_PUBLISHABLE_KEY,
    functionsUrl: import.meta.env.VITE_SUPABASE_FUNCTIONS_URL,
  });

  if (!binding.url || !binding.publishableKey) {
    const message = '[Supabase] Missing authoritative Supabase runtime binding.';
    console.error(message);
    throw new Error(message);
  }

  assertAuthoritativeSupabaseRuntime(binding.url, binding.projectId);
  assertAuthoritativeFunctionsRuntime(binding.functionsUrl);

  return createClient<Database>(binding.url, binding.publishableKey, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
